### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by skies-s** [MulverineX/legacy-settings-icons#1]
_Not working properly! @MulverineX _

**Comment by MulverineX** [comment]
@skies-s try now, was on outdated metadata format

**Comment by MulverineX** [comment]
Also, it works for my friend who's on BD, so I'm not sure what the problem could be. Please let me know what you mean by not working properly.

**Comment by skies-s** [comment]
still says met not found.

**Comment by skies-s** [comment]
![image](https://user-images.githubusercontent.com/68137719/95823657-d01bea80-0d4f-11eb-9896-1c36e61f8970.png)

**Comment by MulverineX** [comment]
@skies-s aight ill get BD loaded up myself

**Comment by skies-s** [comment]
okay!
