### ISSUE TITLE
Icons mismatched

### ISSUE THREAD

**Issue by agnesnutter** [MulverineX/legacy-settings-icons#4]
Not sure if it's the fault of this project or the theme it's being used in, but many of the icons are mismatched.

![Screen Shot 2021-08-24 at 4 17 22 PM](https://user-images.githubusercontent.com/6315656/130683883-b86fad67-86df-4663-bb8a-481ec7b10d8f.png)

**Comment by MulverineX** [comment]
This theme is no longer being maintained, you can try manually fixing, or waiting for Snapperito to update Settings Icons, as it will be able to support BD & Web now that `aria-controls` is built into discord.
